# Generated by Django 3.0.3 on 2020-04-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisifood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
