# Generated by Django 3.0.3 on 2020-04-07 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sisifood', '0002_drink_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='Topping',
            new_name='topping',
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
