# Generated by Django 3.0.3 on 2020-04-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisifood', '0003_auto_20200407_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='id',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
