# Generated by Django 3.0.3 on 2020-04-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisifood', '0005_auto_20200408_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_id',
        ),
        migrations.AddField(
            model_name='pizza',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
