# Generated by Django 3.0.3 on 2020-04-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisifood', '0006_auto_20200408_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(to='sisifood.Topping'),
        ),
    ]
